### ISSUE TITLE
Sprint intro to issues for the virtual hackathon

### ISSUE THREAD

**Issue by jurra** [goscommons/goscommons.github.io#11]
# Hi again! Here we have the list of issues, or work items for contributors. 
## Click the issue you are interested in and mention you want to work on it! Start commenting on that issue and post your ideas, proposals and approach to reach the deliverable or goal you want to reach.
We recommend specially for beginners to partner up with one or two other members. Peering is a best practice when you are learning something new.
### Step-by-step for working on issues:
1. If you haven't, **[download gitkraken](https://www.gitkraken.com/download)**,  a friendly to use interface to manage git. [Learn gitkraken in 5 minutes](https://youtu.be/ZKkMwTeAij4)
2. Explore the issues you are interested in, and decide which one fits your profile.
3. Go to the issue you like and leave a comment that you want to collaborate, this way we can add you as a contributor for the particular repo.
4. Fork the repo and clone it, to get the whole experience of github and collaborative workflows.
5. Make the necessary contribution steps, commits, pull requests, etc. We will help you and assist you the best we can on this one.
6. Finally we check the status of your work, and move it on the [Sprint board](https://github.com/goscommons/goscommons.github.io)

#### Project: Grapple
The grapple is an implement that attaches to the Front End Loader (FEL) of a machinery, for instance a tractor. It requires a separate set of hydraulics in order to operate the open/close (grab/release) function.
List of #issues
- [ ] [Complete wiki home documentation ](https://github.com/goscommons/Grapple/issues/2)
- [ ] [Select a part or several parts and start making technical drawings of the parts](https://github.com/goscommons/Grapple/issues/6)
- [ ] [Complete wiki parts images and links to the files](https://github.com/goscommons/Grapple/issues/5).
 
- [ ] Build parts in other CAD software so that is usable by other user segments, like for instance academics and manufacturers 

#### Project: Microwave
The OS Microwave is a demo repo, to have as a showcase so that others get an idea, of how a repo evolves and grows in content.
List of #issues:
- [x] [Make mechanical drawing of the parts](https://github.com/goscommons/Grapple/issues/6)

- [ ] [Complete wiki parts images and links to the files](https://github.com/goscommons/microwave/wiki/Parts-and-Assembly)

- [x] [Start Filling in bill of materials](https://docs.google.com/spreadsheets/d/12Y4xNs7n5PseNhEt2nXDwRvHf7eEwKK0nqE7WeSsoL0/edit?usp=sharing). This includes materials used, cylinder specs, and prices.

- [ ] Open an issue on manufacturing/ fabrication guidelines and start researching about how the Grapples model can be manufactured locally

#### Project: Vacuum Cleaner
The vacuum cleaner repository is a project that started on May 9th 2018, in a workshop with TU Delft students. In 4 hours they were able to do CAD modeling, understand assembly problems, and analyze the design of the model we had. But it has only started.

### [See the project board available at the Sprint Board](https://github.com/goscommons/vacuum-cleaner/projects/1)

- [ ] Make a first Master CAD with the different parts incorporated, CAD Assembly (open an issue on this) 

- [ ] For students that particpated, open an issue and comment on the design problems they saw (Keep improving the specific issues of the vacuum cleaner towards a good quality contribution) .

- [ ] Start filling the BOM or bill of materials for this project, based on the issues dedicated to each part (this is part of moving the parts related issues accross the project board pipeline).

## For people that want to commit and lead a project, or get deep learning experience.
These are more advanced projects focused on having a working prototype ready for replication.
Leave comment below as well!! :medal_sports: 

- We are also working on an open source tractor.
- A CNC plasma cutter is already quite advanced.

**Comment by krishnarajagopal2011** [comment]
I am interested in microwave project:
- Mechanical drawing of parts
- bill of materials

**Comment by goscommons** [comment]
Great @krishnarajagopal2011 I will add you right on

**Comment by goscommons** [comment]
Would you like to start with CNC?
